CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Author" text NOT NULL,
    "Genre" text NOT NULL,
    "ExchangeStatus" text NOT NULL,
    "AvailableCount" integer NOT NULL,
    "TotalCount" integer NOT NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id")
);

CREATE TABLE "Borrowings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BookTitle" text NOT NULL,
    "RealName" text NOT NULL,
    "TelegramName" text NOT NULL,
    "Contact" text NOT NULL,
    "IssueDate" timestamp with time zone NOT NULL,
    "ReturnDate" timestamp with time zone,
    "ChatId" bigint NOT NULL,
    "DueDate" timestamp with time zone NOT NULL,
    "IsExtended" boolean NOT NULL,
    CONSTRAINT "PK_Borrowings" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260609141622_InitialCreate', '10.0.8');

COMMIT;

